// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrgHAlbGFu-Qq5Rf6AVskUZc0IzTddh4',
    appId: '1:267891791886:android:65937563d9007d42adc45f',
    messagingSenderId: '267891791886',
    projectId: 'eat-it-here',
    storageBucket: 'eat-it-here.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnt0pQAJyEEWYxuY_dltyPexSOBCG-uZ8',
    appId: '1:267891791886:ios:5a8fac5abcd2b08fadc45f',
    messagingSenderId: '267891791886',
    projectId: 'eat-it-here',
    storageBucket: 'eat-it-here.firebasestorage.app',
    iosBundleId: 'com.example.eatItHere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATvSKcqDcvZ0yae1QI9b2LMn7LdNAZkAM',
    appId: '1:267891791886:web:4df51c857c3c0705adc45f',
    messagingSenderId: '267891791886',
    projectId: 'eat-it-here',
    authDomain: 'eat-it-here.firebaseapp.com',
    storageBucket: 'eat-it-here.firebasestorage.app',
    measurementId: 'G-SRTJ2VB2VM',
  );
}
